# Action name
name: Android Build

# Actions to run when a pull request is performed
on: pull_request

# Tasks
jobs:
  build:

    # Enviroment to tun
    runs-on: ubuntu-latest

    # Steps
    steps:
      - uses: actions/checkout@v1
        # Setup tooling and environment
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

        # Define Android specific tasks
      - name: Run Tests
        run: ./gradlew test


      - name: Build Project
        run: ./gradlew assemble

  # Parallel job
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Instrumentation Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew connectedAndroidTest


